server:
  port: 8081
  servlet:
    context-path: /testdemo
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
    view:
      prefix: webapp
      suffix: .jsp
spring:
  #redis
#  redis:
#    database: 0
#    host: 192.168.150.129
#    port: 6379
#    password: 123456
#    jedis:
#       pool:
#          max-active: 100
#          max-idle: 3
#          max-wait: -1
#          min-idle: 0
#    timeout: 1000

  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
       #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        #deny: 192.168.1.100

#Mybatis配置
mybatis:
     #配置SQL映射文件路径
     mapper-locations: classpath:mapper/*.xml
     #配置别名
     type-aliases-package: com.kk.testdemo.model
     #驼峰命名
     configuration:
        map-underscore-to-camel-case: true
#显示日志
logging:
  level:
    com.kk.testdemo.mapper: debug
#pagehelper分页插件配置
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql






